#!/bin/sh
# install-deps.sh — zero-sudo build environment setup for Debian 13.
#
# Everything needed to build this project is available without root:
#   1. rustup (user-local Rust toolchain, no root)
#   2. dev symlinks for the system runtime libs cargo may link against
#      (mimics what the -dev packages would provide, but in ~/.local/lib)
#   3. .cargo/config.toml pointing rustc at rust-lld + system crt objects,
#      so no C compiler or pkg-config is required.
#
# Nothing else is needed: .docx content search uses an in-process OOXML
# extractor (no `docx2txt`).
set -e

MULTIARCH=/usr/lib/x86_64-linux-gnu
LOCALLIB="$HOME/.local/lib"
PROJECT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"

echo "==> 1/3 dev symlinks in $LOCALLIB"
mkdir -p "$LOCALLIB"
for pair in \
  "libdl.so.2:libdl.so" \
  "libgcc_s.so.1:libgcc_s.so" \
  "libwayland-client.so.0:libwayland-client.so" \
  "libwayland-cursor.so.0:libwayland-cursor.so" \
  "libwayland-egl.so.1:libwayland-egl.so" \
  "libxkbcommon.so.0:libxkbcommon.so" \
  "libEGL.so.1:libEGL.so" \
  "libGL.so.1:libGL.so" \
  "libGLX.so.0:libGLX.so" \
  "libgbm.so.1:libgbm.so" \
  "libX11.so.6:libX11.so" \
  "libXcursor.so.1:libXcursor.so" \
  "libXrandr.so.2:libXrandr.so" \
  "libXi.so.6:libXi.so" \
  "libxkbcommon-x11.so.0:libxkbcommon-x11.so" \
  "libfontconfig.so.1:libfontconfig.so" ; do
  src="$MULTIARCH/${pair%%:*}"; dst="$LOCALLIB/${pair##*:}"
  if [ -e "$src" ]; then
    ln -sfn "$src" "$dst"
  else
    echo "    (skip: $src not present)"
  fi
done

echo "==> 2/3 Rust toolchain (rustup, user-local)"
if [ -x "$HOME/.cargo/bin/cargo" ]; then
  echo "    cargo already present: $($HOME/.cargo/bin/cargo --version)"
elif command -v cargo >/dev/null 2>&1; then
  echo "    cargo already present: $(cargo --version)"
else
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
fi

echo "==> 3/3 .cargo/config.toml + linker wrapper"
chmod +x "$PROJECT_DIR/scripts/rust-lld-wrapper.sh"
mkdir -p "$PROJECT_DIR/.cargo"
cat > "$PROJECT_DIR/.cargo/config.toml" <<EOF
# Generated by scripts/install-deps.sh for this machine.
# Links Rust binaries with rustup's bundled rust-lld + system crt objects,
# so no C compiler / pkg-config is required. If your setup differs, re-run
# scripts/install-deps.sh to regenerate this file.
[target.x86_64-unknown-linux-gnu]
linker = "$PROJECT_DIR/scripts/rust-lld-wrapper.sh"
rustflags = [
  "-C", "link-arg=$MULTIARCH/crt1.o",
  "-C", "link-arg=$MULTIARCH/crti.o",
  "-C", "link-arg=$MULTIARCH/crtn.o",
  "-C", "link-arg=--dynamic-linker=/lib64/ld-linux-x86-64.so.2",
  "-C", "link-arg=-L$MULTIARCH",
  "-C", "link-arg=-L$LOCALLIB",
]
EOF

echo "==> 4/4 ~/.gitignore (non-essential folders excluded from indexing)"
if [ ! -f "$HOME/.gitignore" ]; then
  cp "$PROJECT_DIR/.gitignore" "$HOME/.gitignore"
  echo "    installed $HOME/.gitignore"
else
  echo "    $HOME/.gitignore already exists (leaving it untouched)"
fi

echo ""
echo "Done. Build with:"
echo "    cd \"$PROJECT_DIR\" && cargo build --release"
