#!/bin/sh
# rust-lld-wrapper — cargo linker wrapper for the zero-sudo build setup.
#
# Why: the project's .cargo/config.toml links with rustup's bundled rust-lld
# plus the system crt objects (crt1.o/crti.o/crtn.o) and an explicit dynamic
# linker, because no C compiler is installed. Since the configured linker is
# not named exactly "rust-lld", rustc invokes it with gcc-style arguments
# (-Wl,... groups, -fuse-ld, -nodefaultlibs, -B gcc-ld dir, ...). This wrapper:
#   1. translates those arguments to ld.lld-style,
#   2. drops the crt/startup arguments for -shared links (cdylib/proc-macro
#      crates), where they are neither needed nor valid.
#
# Regenerated by scripts/install-deps.sh.

SHARED=0
for a in "$@"; do
  case "$a" in
    -shared|--shared) SHARED=1 ;;
  esac
done

LLD=""
for cand in "$HOME"/.rustup/toolchains/*/lib/rustlib/*/bin/rust-lld; do
  [ -x "$cand" ] && LLD="$cand"
done
if [ -z "$LLD" ]; then
  echo "rust-lld-wrapper: rust-lld not found under \$HOME/.rustup" >&2
  exit 1
fi

args=""
for a in "$@"; do
  case "$a" in
    -m64|-fuse-ld=*|-nodefaultlibs)
      ;; # gcc-only; drop
    -Bstatic|-Bdynamic)
      args="$args $a"
      ;;
    -B*)
      ;; # gcc sysroot/gcc-ld search dir; drop (crt is passed by absolute path)
    -Wl,*)
      # split -Wl,a,b,c into a b c
      rest="${a#-Wl,}"
      oldIFS="$IFS"; IFS=','
      for piece in $rest; do
        args="$args $piece"
      done
      IFS="$oldIFS"
      ;;
    */crt1.o|*/crti.o|*/crtn.o|--dynamic-linker=*)
      if [ "$SHARED" != "1" ]; then
        args="$args $a"
      fi
      ;;
    *)
      args="$args $a"
      ;;
  esac
done

# shellcheck disable=SC2086
exec "$LLD" -flavor gnu $args
